# Generated by Django 5.1.3 on 2024-11-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_ctaegory'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root.manager')),
                ('stars', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root.score')),
            ],
        ),
    ]
